num = input('Digite algo: ')
print('O tipo primitivo do valor digitado é:', type(num))
print('É um valor númerico?', num.isnumeric())
print('Só tem espaços?:', num.isspace())
print('É um valor alfabético?', num.isalpha())
print('É um valor alfanumérico?:', num.isalnum())
print('Está em maíusculas?:', num.isupper())
print('Está em minusculas?:', num.islower())
print('Está em capitalizada?:', num.istitle())